Repository kubernetes-sigs/contributor-tweets, pull requests merged in 2020-08, with the labels that each got.

#5 Updated README
  GUIDELINES.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#6 Removed merge schedule action workflow
  .github/workflows/merge-schedule.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7 Tweet for lifecycle survey
  tweets/17-08-2020-lifecycle-survey.tweet
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8 Contributor site launch
  tweets/24-08-2020-contributor-site.tweet
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash
