Repository kubernetes-sigs/contributor-tweets, pull requests merged in 2021-06, with the labels that each got.

#33 feat: add automation scripts for the tweet action
  .github/assets/ISSUE_TEMPLATE/new-tweet-request.md
  .github/workflows/main.yml
  .github/workflows/twitter-together.yaml
  .gitignore
  OWNERS
  README.md
  action.yaml
  index.js
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XL, tide/merge-method-squash

#44 Monthly Community Meeting Tweet
  tweets/2021-06-14-contributor-meeting.tweet
Labels: approved, cncf-cla: yes, lgtm, size/XS

#43 Fix: Automated Tweet via Issue
  .github/ISSUE_TEMPLATE/new-tweet-request.md
  .github/workflows/main.yml
  index.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#47 Fix tweet action workflow
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
